# Configuration for the project-goals code

[team_asks]
"Allocate funds" = "allocate funding"
"Discussion and moral support" = "approve of this direction and be prepared for light discussion on Zulip or elsewhere"
"Design meeting" = "hold a synchronous meeting to review a proposal and provide feedback (no decision expected)"
"Stabilization decision" = "reach a decision on a stabilization proposal"
"Prioritized nominations" = "prioritize discussion and resolution of nominated issues"
"Deploy to production" = "deploy code to production (e.g., on crates.io"
"Standard reviews" = "review PRs (PRs are not expected to be unduly large or complicated)"
"Dedicated reviewer" = "assign a specific person (or people) to review a series of PRs, appropriate for large or complex asks"
"Lang-team experiment" = "begin a [lang-team experiment](https://lang-team.rust-lang.org/how_to/experiment.html) authorizing experimental impl of lang changes before an RFC is written; limited to trusted contributors"
"RFC decision" = "review an RFC and deciding whether to accept"
"RFC secondary review" = "briefly review an RFC without need of a formal decision"
"Org decision" = "reach a decision on an organizational or policy matter"
"MCP decision" = "accept a [Major Change Proposal](https://forge.rust-lang.org/compiler/mcp.html)"
"ACP decision" = "accept an [API Change Proposal](https://std-dev-guide.rust-lang.org/development/feature-lifecycle.html)"
"Policy decision" = "make a decision related to team policy"
"FCP decision(s)" = "make formal decision(s) that require 'checkboxes' and a FCP (Final Comment Period)"
"Blog post approval" = "approve of posting about this on the main Rust blog"
"Miscellaneous" = "do some one-off action as described in the notes"
